### PR TITLE
Ps1854

### PR DESCRIPTION
**Pull request by ps1854**

### CODE REVIEW

**Comment by Nandani-Paliwal** [comment]
Hello, @ps1854  Your Readme is wonderful, but it would be even better if you added a brief introduction of yourself, so that others can get a fast overview of who you are by reading it.

**Comment by ps1854** [comment]
Okay. I'll try to add that. Thank you.

**Review by Panquesito7 — APPROVED** [review]
Awesome! 🚀 Thanks for contributing.

**Comment by Nandani-Paliwal** [comment]
@ps1854 Thankyou for contributing ✨

**Pull request merged**
